### ISSUE TITLE
The package is hardly usable with vc142 toolset and/or x64-bit config

### ISSUE THREAD

**Issue by Anton-V-K** [MikeAirey/log4cpp#1]
There is no support of x64 bit configuration in the version 1.1.3 - no binaries for this platform at all :(

And building with vc142 requires extra manual step - copying `\log4cpp.1.1.3\lib\native\v141` into `\log4cpp.1.1.3\lib\native\v142`, which is a bit inconvenient.
Since the toolsets vc140 - vc142 are binary-compatible, it makes sense to keep only lowest version.

**Comment by MikeAirey** [comment]
I don't have a lot of time to work on this for wider applicability, but I'll see what I can do. Alternatively feel free to open a PR if you have got a solution working locally and would like to contribute it. Thanks!

**Comment by MikeAirey** [comment]
Added support for vc142 toolset. x64 support is unfortunately outside the scope of the time I have available at the moment. New package release available at: https://www.nuget.org/packages/log4cpp/1.1.3.1

**Comment by Anton-V-K** [comment]
I've managed to add x64 support to `BuildNugetPackage.vcxproj` and tested it with my x64 project. Everything seems to be working fine.
The attached archive [log4cpp-nuget-x64-support.zip](https://github.com/MikeAirey/log4cpp/files/7490212/log4cpp-nuget-x64-support.zip) contains the modified files (`BuildNugetPackage.cmd` and `BuildNugetPackage.vcxproj`).

I would also modify `nuget\build\log4cpp.targets` to replace `$(PlatformToolset)` with hardcoded value `v142` to support easy building with older compatible toolsets (in VS2017 or even VS2015) without extra local modifications (it is hardly possible for x64 configuration due to [newer exceptions handling](https://stackoverflow.com/questions/65672356/what-is-cxxframehandler4-and-what-does-linker-error-unresolved-external-symbo), but with Win32 it may work).
As mentioned in the comments under the [atricle "Making C++ Exception Handling Smaller On x64"](https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/) it is still possible to disable FH4 (which is enabled by default in 16.3 and beyond):

> VS2019->Properties->C/C++->Command Line add ‘-d2FH4-‘
> VS2019->Properties->Linker->Command Line add ‘-d2:-FH4-‘

Unfortunately I couldn't find an easy way how to pass this option through cmake to log4cpp - the obvious approach like `cmake -D CMAKE_CXX_FLAGS="-d2FH4-"` doesn't work as expected (the default flags are erased).

**Comment by MikeAirey** [comment]
Thanks for continuing to investigate this, Anton. I'll create a new issue for adding 64-bit support and integrate your changes there when I have time, likely to be January at this rate.
